# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.nllh_bvn_censored_ogram <- function(pars, x, y, ux, uy, freq) {
    .Call(`_deform_nllh_bvn_censored_ogram`, pars, x, y, ux, uy, freq)
}

.cnorml <- function(pars, yvec, lvec) {
    .Call(`_deform_cnorml`, pars, yvec, lvec)
}

.cnormr <- function(pars, yvec, rvec) {
    .Call(`_deform_cnormr`, pars, yvec, rvec)
}

.cnormlr <- function(pars, yvec, lvec, rvec) {
    .Call(`_deform_cnormlr`, pars, yvec, lvec, rvec)
}

.coscovfn <- function(pars, X, n) {
    .Call(`_deform_coscovfn`, pars, X, n)
}

.d1coscovfn <- function(pars, X, n) {
    .Call(`_deform_d1coscovfn`, pars, X, n)
}

.d2coscovfn <- function(pars, X, n) {
    .Call(`_deform_d2coscovfn`, pars, X, n)
}

.covfn <- function(pars, X, n) {
    .Call(`_deform_covfn`, pars, X, n)
}

.d1covfn <- function(pars, X, n) {
    .Call(`_deform_d1covfn`, pars, X, n)
}

.d2covfn <- function(pars, X, n) {
    .Call(`_deform_d2covfn`, pars, X, n)
}

.dampedcoscovfn <- function(pars, X, n) {
    .Call(`_deform_dampedcoscovfn`, pars, X, n)
}

.d1dampedcoscovfn <- function(pars, X, n) {
    .Call(`_deform_d1dampedcoscovfn`, pars, X, n)
}

.d2dampedcoscovfn <- function(pars, X, n) {
    .Call(`_deform_d2dampedcoscovfn`, pars, X, n)
}

.pcovfn <- function(pars, z, n) {
    .Call(`_deform_pcovfn`, pars, z, n)
}

.pcoscovfn <- function(pars, z, n) {
    .Call(`_deform_pcoscovfn`, pars, z, n)
}

.punitcoscovfn <- function(pars, z, n) {
    .Call(`_deform_punitcoscovfn`, pars, z, n)
}

.punitcovfn <- function(pars, z, n) {
    .Call(`_deform_punitcovfn`, pars, z, n)
}

.pdampedcoscovfn <- function(pars, z, n) {
    .Call(`_deform_pdampedcoscovfn`, pars, z, n)
}

.tnormr <- function(pars, yvec, rvec) {
    .Call(`_deform_tnormr`, pars, yvec, rvec)
}

.tnorml <- function(pars, yvec, lvec) {
    .Call(`_deform_tnorml`, pars, yvec, lvec)
}

.tnormlr <- function(pars, yvec, lvec, rvec) {
    .Call(`_deform_tnormlr`, pars, yvec, lvec, rvec)
}

.unitcoscovfn <- function(pars, X, n) {
    .Call(`_deform_unitcoscovfn`, pars, X, n)
}

.d1unitcoscovfn <- function(pars, X, n) {
    .Call(`_deform_d1unitcoscovfn`, pars, X, n)
}

.d2unitcoscovfn <- function(pars, X, n) {
    .Call(`_deform_d2unitcoscovfn`, pars, X, n)
}

.unitcovfn <- function(pars, X, n) {
    .Call(`_deform_unitcovfn`, pars, X, n)
}

.d1unitcovfn <- function(pars, X, n) {
    .Call(`_deform_d1unitcovfn`, pars, X, n)
}

.d2unitcovfn <- function(pars, X, n) {
    .Call(`_deform_d2unitcovfn`, pars, X, n)
}

